### ISSUE TITLE
Errors in our builds

### ISSUE THREAD

**Issue by lee5i3** [sematext/logsene-js#14]
We are getting the following:
[14:15:28][Step 3/4] /opt/teamcity_agent/work/5b977a51079a5e19/node_modules/logsene-js/index.js:345
[14:15:28][Step 3/4]       host_ip: ipAddress
[14:15:28][Step 3/4]       ^^^^^^^
[14:15:28][Step 3/4] 
[14:15:28][Step 3/4] SyntaxError: Unexpected identifier
[14:15:28][Step 3/4]     at createScript (vm.js:80:10)
[14:15:28][Step 3/4]     at Object.runInThisContext (vm.js:139:10)
[14:15:28][Step 3/4]     at Module._compile (module.js:617:28)
[14:15:28][Step 3/4]     at Object.Module._extensions..js (module.js:664:10)
[14:15:28][Step 3/4]     at Module.load (module.js:566:32)
[14:15:28][Step 3/4]     at tryModuleLoad (module.js:506:12)
[14:15:28][Step 3/4]     at Function.Module._load (module.js:498:3)
[14:15:28][Step 3/4]     at Module.require (module.js:597:17)
[14:15:28][Step 3/4]     at require (internal/module.js:11:18)
[14:15:28][Step 3/4]     at Object.<anonymous> (/opt/teamcity_agent/work/5b977a51079a5e19/node_modules/winston-logsene/lib/index.js:7:17)
[14:15:28][Step 3/4] npm ERR! Test failed.  See above for more details.

Looks like there was a change in your code with no PR..
https://github.com/sematext/logsene-js/blob/e8ce6e49af2c5d0aaf769298e9bcd37e39d8542e/index.js#L344-L345
Missing a comma at line 344

**Comment by lee5i3** [comment]
Added PR fix
https://github.com/sematext/logsene-js/pull/15

**Comment by megastef** [comment]
@lee5i3 Thank you for reporting the issue & the PR.  We just released 1.1.60 on npm. 
We updated mocha test as well.
