### ISSUE TITLE
throws error and causes app to crash when sematext server is down

### ISSUE THREAD

**Issue by joonhocho** [sematext/logsene-js#17]
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  source: 'logsene-js',
  err: {
    message: 'HTTP status code:503',
    httpStatus: 503,
    httpBody: '<html>\r\n' +
      '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
      '<hr><center>nginx/1.17.10</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n',
    url: 'https://logsene-receiver.sematext.com/_bulk'
  }
})
    at Logsene.emit (events.js:304:17)
    at Logsene.EventEmitter.emit (domain.js:485:12)
    at Request.httpResult [as _callback] (index.js:462:12)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
```

**Comment by joonhocho** [comment]
Needs proper error handling so it doesn't crash

**Comment by joonhocho** [comment]
currently sematext server seems down and is causing my app to crash :(

**Comment by adnanrahic** [comment]
Hey @joonhocho ! Thanks for creating an issue. I'm aware of this and have it on my todo list to handle ASAP. :ok_hand:

**Comment by joonhocho** [comment]
@adnanrahic Thanks!

**Comment by adnanrahic** [comment]
Hi @joonhocho . I've released a new version of the agent with a fix for this issue.
Can you please check out version [1.1.70](https://github.com/sematext/logsene-js/releases/tag/1.1.70) and confirm it works for you?
